const ShopActionTypes = {
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
  LOAD_COLLECTIONS_START: 'LOAD_COLLECTIONS_START',
  LOAD_COLLECTIONS_SUCCESS: 'LOAD_COLLECTIONS_SUCCESS',
};

export default ShopActionTypes;
